name: Build

on:
  push:
  pull_request:
  merge_group:
    types: [checks_requested]
  # allow manual triggering
  workflow_dispatch:

jobs:
  debug-release-layout:
    name: Debug the release artifact layout
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          run-id: 10971058923  # ${{ needs.build.outputs.run_id }}
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          path: tmp/release

      - name: Debug
        run: pwd && ls -alFR tmp/release
